### ISSUE TITLE
async error

### ISSUE THREAD

**Issue by mycaule** [botpress/Boost#14]
Got this error when trying to run `botpress start`, running node v6.10.3 LTS :

```
ams:Boost michel$ botpress start
18:40:33 - info: Starting botpress version 0.2.2
18:40:33 - info: Loaded botpress-analytics, version 2.0.7
18:40:33 - info: Loaded botpress-broadcast, version 2.0.9
18:40:33 - info: Loaded botpress-dialog, version 1.0.17
18:40:33 - info: Loaded botpress-messenger, version 2.0.15
18:40:33 - info: Loaded botpress-rivescript, version 2.0.5
18:40:33 - info: Loaded botpress-scheduler, version 2.0.7
18:40:33 - info: Loaded botpress-subscription, version 2.0.6
18:40:33 - info: Loaded botpress-terminal, version 1.0.2
18:40:33 - info: Loaded 8 modules
/Users/michel/Code/Sandbox/Boost/subscription.js:26
  const token = await bp.security.login('admin', bp.botfile.login.password, '127.0.0.1')
                      ^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michel/Code/Sandbox/Boost/index.js:4:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at botpress._start (/Users/michel/Code/Sandbox/Boost/node_modules/botpress/lib/webpack:/src/botpress.js:191:26)
    at botpress.start (/Users/michel/Code/Sandbox/Boost/node_modules/botpress/lib/webpack:/src/botpress.js:236:12)
    at Command.module.exports (/Users/michel/.nvm/versions/node/v6.10.3/lib/node_modules/botpress/lib/webpack:/src/cli/start.js:45:7)
    at Command.listener (/Users/michel/.nvm/versions/node/v6.10.3/lib/node_modules/botpress/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
```

**Comment by slvnperron** [comment]
You should run boost using `node >= 7`. Hope this helps
